# Generated by Django 6.0 on 2026-01-10 06:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_blog_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimage',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='extra image'),
        ),
    ]
