# Generated by Django 5.2.3 on 2025-08-27 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_blog_delete_blogs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Blog Post', 'verbose_name_plural': 'Blog Posts'},
        ),
        migrations.AlterModelOptions(
            name='internship',
            options={'ordering': ['-timeStamp'], 'verbose_name': 'Internship', 'verbose_name_plural': 'Internships'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='phonenumber',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='internship',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='internship',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='internship',
            name='offer_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], max_length=60),
        ),
        migrations.AlterField(
            model_name='internship',
            name='proj_report',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='internship',
            name='usn',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
